import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./navbar";
import { Container, Theme, ThemePanel } from "@radix-ui/themes";
import { ThemeProvider } from "./components/ThemeProvider";
import AuthSession from "./auth/Provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <AuthSession>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Theme accentColor="violet" radius="large">
            <Navbar />
            <main>
              {children}
            </main>
            {/* <ThemePanel /> */}
          </Theme>
        </ThemeProvider>
        </AuthSession>
      </body>
    </html>
  );
}
